import {
  boolean,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  vector,
} from 'drizzle-orm/pg-core'

// schema for this project is defined in this file, and used in drizzle.config.ts to generate the migration files

// the users table schema
// Auth.0 — one row per person using the app. A guest is a real row too, just
// with no email and no password (isGuest = true). That way a guest's token
// goes through exactly the same checks as a registered user's, and signing up
// later only fills in email + passwordHash on the SAME row, so the guest's
// documents and chats stay theirs.
export const users = pgTable('users', {
  id: text('id').primaryKey(), // uuid, same style as documents.id
  // null for guests. UNIQUE still works: Postgres treats every NULL as
  // different from every other NULL, so many guests can all have no email.
  email: text('email').unique(),
  // null for guests. Never the password itself, only its bcrypt hash.
  passwordHash: text('password_hash'),
  isGuest: boolean('is_guest').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})
// equivalent sql query:
// CREATE TABLE users (
//   id TEXT PRIMARY KEY,
//   email TEXT UNIQUE,
//   password_hash TEXT,
//   is_guest BOOLEAN NOT NULL DEFAULT TRUE,
//   created_at TIMESTAMP NOT NULL DEFAULT NOW()
// )

// the documents table schema
// One row per uploaded PDF, tracks metadata so the frontend (or Postman,
// or any other client) can list "what documents exist" without deriving it
// from chunk rows, and without depending on whoever uploaded it.
export const documents = pgTable('documents', {
  id: text('id').primaryKey(), // same UUID used as chunks.document_id
  filename: text('filename').notNull(),
  fileSizeBytes: integer('file_size_bytes').notNull(),
  textLength: integer('text_length').notNull(),
  chunkCount: integer('chunk_count').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  // Auth.0 — who uploaded this document. Nullable on purpose: adding a
  // nullable column to a live table is instant and doesn't break the code
  // that's already deployed (it just never fills it in). A row with no owner
  // matches no user, so nobody can see it.
  userId: text('user_id'),
  // BG.0 — where the document is in its life: 'processing' (row exists, the
  // queue worker is still embedding its chunks), 'ready' (fully searchable)
  // or 'failed' (every retry used up). Only 'ready' documents are searched or
  // quizzed. DEFAULT 'ready' is what made the SQL below safe on the live
  // table: every existing row became ready instantly, and the code deployed
  // before BG never writes this column, so its uploads are ready too.
  status: text('status').notNull().default('ready'), // 'processing' | 'ready' | 'failed'
  // BG.0 — a short, user-safe reason when status = 'failed' (never a stack
  // trace or SQL; the full error goes to the terminal via summarizeError()).
  error: text('error'),
})
// equivalent sql query (Auth.0):
// ALTER TABLE documents ADD COLUMN user_id TEXT;
// CREATE INDEX documents_user_id_idx ON documents (user_id);
// (BG.0):
// ALTER TABLE documents ADD COLUMN status TEXT NOT NULL DEFAULT 'ready';
// ALTER TABLE documents ADD COLUMN error TEXT;

// the chunks table schema
// Auth.0 — chunks deliberately get NO user_id. A chunk belongs to a document
// and the document has the owner, so searches filter on documents.user_id
// through the join searchSimilar already does.
// this chunks table is used to store the text chunks and their corresponding embeddings. Each chunk is associated with a document via the documentId column, allowing for grouping and retrieval of chunks by document. The embedding column is defined as a vector type with 3072 dimensions, which is suitable for storing the embeddings generated by the Gemini AIP
// defined the table as typescript type
export const chunks = pgTable('chunks', {
  // The 'id' column is defined as a serial type and is the primary key of the table, always incremented by 1 for each new row
  id: serial('id').primaryKey(),
  // The 'content' column is defined as a text type and cannot be null
  content: text('content').notNull(),
  // The 'embedding' column is defined as a vector type with 3072 dimensions
  embedding: vector('embedding', { dimensions: 3072 }),
  // document_id keeps track of which document the chunk belongs to, allowing for grouping and retrieval of chunks by document
  documentId: text('document_id').notNull(),
})

// every other file will import this file (chunks) and use it to access the table and its columns in a type-safe manner
// this allows for better code completion and type checking when working with the database schema in TypeScript

// the chatMessages table
// Step 2.4 — one row per message in a conversation. sessionId groups
// messages into one conversation thread; documentId is stored too so a
// session's history is always tied back to which document it's about.
export const chatMessages = pgTable('chat_messages', {
  id: serial('id').primaryKey(),
  sessionId: text('session_id').notNull(),
  // documentId keeps track of which document the message belongs to
  documentId: text('document_id').notNull(),
  // 
  role: text('role').notNull(), // 'user' | 'assistant'
  content: text('content').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  // Auth.0 — who this message belongs to. Unlike chunks, messages DO need
  // their own owner column: an "All documents" session has document_id =
  // 'all', so there's no document row to find the owner through.
  userId: text('user_id'),
})
// equivalent sql query:
// CREATE TABLE chat_messages (
//   id SERIAL PRIMARY KEY,
//   session_id TEXT NOT NULL,
//   document_id TEXT NOT NULL,
//   role TEXT NOT NULL,
//   content TEXT NOT NULL,
//   created_at TIMESTAMP NOT NULL DEFAULT NOW()
// )
// (Auth.0):
// ALTER TABLE chat_messages ADD COLUMN user_id TEXT;
// CREATE INDEX chat_messages_user_session_idx ON chat_messages (user_id, session_id);